#!/usr/bin/env node
// Syncs the compiled LimitOrderBook ABI from forge output into packages/shared.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = JSON.parse(
  readFileSync(join(root, "contracts/out/LimitOrderBook.sol/LimitOrderBook.json"), "utf8"),
);

const out = `// Auto-generated by scripts/sync-abi.mjs — do not edit by hand.
export const LIMIT_ORDER_BOOK_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
writeFileSync(join(root, "packages/shared/src/abi.ts"), out);
console.log(`synced ${artifact.abi.length} ABI entries → packages/shared/src/abi.ts`);
